export const enum ActionType {
  CHECKBOX_CLICKED = 'CHECKBOX_CLICKED',
  GET_TICKETS = 'GET_TICKETS',
  SET_NUMBER_TO_SHOW = 'SET_NUMBER_TO_SHOW',
  SET_CHEAPEST = 'SET_CHEAPEST',
  SET_FASTEST = 'SET_FASTEST',
}
